/**
 * LLM Adapter Layer
 *
 * Three exported functions — one per pipeline pass.
 * Each switches on ProviderName and calls the correct API.
 * Adding a new provider = add a case in the switch + a private helper. Nothing else changes.
 *
 * Prompts are preserved exactly from the original geminiVision.ts.
 */

import type { ParsedReceipt } from '../types/receipt.types';
import type { ProviderName } from '../types/providers';
import type { PassTokens } from '../monitoring/tokenCost';
import _autoCorrections from '../data/autoLearnedCorrections.json';

// Nested format: { "_global": { ocrText: correct }, "restaurant key": { ocrText: correct } }
// Generated by `npm run regression:learn` — bundled at build time by Vite.
const AUTO_CORRECTIONS = _autoCorrections as Record<string, Record<string, string>>;

/**
 * Apply auto-learned corrections to every item name in the receipt.
 * Looks up corrections in two scopes (merged, scoped wins on conflict):
 *   1. "_global" — applies to every receipt regardless of restaurant
 *   2. restaurantKey — restaurant-specific corrections from the golden files
 */
function applyAutoCorrections(receipt: ParsedReceipt): ParsedReceipt {
  const global     = AUTO_CORRECTIONS['_global'] ?? {};
  const restaurantKey = receipt.restaurantName?.trim().toLowerCase() ?? '';
  const scoped     = restaurantKey ? (AUTO_CORRECTIONS[restaurantKey] ?? {}) : {};
  const combined   = { ...global, ...scoped }; // scoped overrides global on conflict
  if (!Object.keys(combined).length) return receipt;
  return {
    ...receipt,
    items: receipt.items.map(item => ({
      ...item,
      name: combined[item.name] ?? item.name,
    })),
  };
}

// ─── Gemini helpers ───────────────────────────────────────────────────────────

const GEMINI_KEY = import.meta.env.VITE_GEMINI_API_KEY as string;

function geminiUrl(model: string): string {
  return `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_KEY}`;
}

function geminiModelName(provider: ProviderName): string {
  switch (provider) {
    case 'gemini-2.5-flash': return 'gemini-2.5-flash';
    case 'gemini-1.5-pro':   return 'gemini-1.5-pro';
    case 'gemini-2.0-flash':
    default:                 return 'gemini-2.0-flash';
  }
}

async function geminiParseQuotaError(res: Response): Promise<never> {
  try {
    const body = await res.json();
    const violations: Array<{ quotaId?: string }> =
      body?.error?.details?.find((d: Record<string, unknown>) =>
        d['@type']?.toString().includes('QuotaFailure')
      )?.violations ?? [];
    const isDaily = violations.some(v => v.quotaId?.includes('PerDay'));
    const delay   = body?.error?.details?.find(
      (d: Record<string, unknown>) => d.retryDelay
    )?.retryDelay as string | undefined;
    throw new Error(
      isDaily ? 'DAILY_QUOTA_EXCEEDED'
      : delay  ? `TOO_MANY_REQUESTS:${delay}`
      :          'TOO_MANY_REQUESTS'
    );
  } catch (e) {
    if (e instanceof Error &&
       (e.message.startsWith('TOO_MANY_REQUESTS') || e.message === 'DAILY_QUOTA_EXCEEDED')) throw e;
    throw new Error('TOO_MANY_REQUESTS');
  }
}

// ─── Anthropic helpers ────────────────────────────────────────────────────────

const ANTHROPIC_KEY = import.meta.env.VITE_ANTHROPIC_API_KEY as string;

// Dev  → Vite reverse-proxy at /api/anthropic  (vite.config.ts server.proxy, no CORS)
// Prod → Cloudflare Worker  (set VITE_ANTHROPIC_PROXY_URL=https://xxx.workers.dev)
const ANTHROPIC_URL = import.meta.env.DEV
  ? '/api/anthropic/v1/messages'
  : `${import.meta.env.VITE_ANTHROPIC_PROXY_URL ?? ''}/v1/messages`;

function anthropicModelName(provider: ProviderName): string {
  switch (provider) {
    case 'claude-sonnet-4-5':
    default: return 'claude-sonnet-4-5';
  }
}

// ─── Pass 1: transcribeImage ──────────────────────────────────────────────────

export async function transcribeImage(
  imageBase64: string,
  mimeType: string,
  provider: ProviderName,
): Promise<{ transcript: string; tokens: PassTokens }> {
  switch (provider) {
    case 'gemini-2.0-flash':
    case 'gemini-2.5-flash':
    case 'gemini-1.5-pro':
      return _geminiTranscribe(imageBase64, mimeType, geminiModelName(provider));
    case 'claude-sonnet-4-5':
      return _claudeTranscribe(imageBase64, mimeType);
  }
}

async function _geminiTranscribe(
  imageBase64: string,
  mimeType: string,
  model: string,
): Promise<{ transcript: string; tokens: PassTokens }> {
  const res = await fetch(geminiUrl(model), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{
        parts: [
          { inline_data: { mime_type: mimeType, data: imageBase64 } },
          { text: TRANSCRIPT_PROMPT },
        ],
      }],
      generationConfig: {
        maxOutputTokens: 8192,
        temperature: 0,
        thinkingConfig: { thinkingBudget: 0 },
      },
    }),
  });

  if (!res.ok) {
    if (res.status === 429) await geminiParseQuotaError(res);
    throw new Error(`HTTP_${res.status}`);
  }

  const json         = await res.json();
  const finishReason = json.candidates?.[0]?.finishReason ?? '';
  const text         = (json.candidates?.[0]?.content?.parts?.[0]?.text ?? '').trim();

  if (!text) throw new Error(finishReason === 'MAX_TOKENS' ? 'BLURRY' : finishReason === 'OTHER' ? 'MODEL_ABORTED' : 'EMPTY_RESPONSE');
  if (text.startsWith('NOT_A_RECEIPT')) throw new Error('NOT_A_RECEIPT');
  if (text.startsWith('BLURRY'))        throw new Error('BLURRY');

  const words    = text.split(/\s+/);
  const unknowns = words.filter((w: string) => w === '[?]').length;
  if (unknowns / words.length > 0.5) throw new Error('BLURRY');

  return {
    transcript: text,
    tokens: {
      inputTokens:  json.usageMetadata?.promptTokenCount     ?? 0,
      outputTokens: json.usageMetadata?.candidatesTokenCount ?? 0,
    },
  };
}

async function _claudeTranscribe(
  imageBase64: string,
  mimeType: string,
): Promise<{ transcript: string; tokens: PassTokens }> {
  const res = await fetch(ANTHROPIC_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_KEY,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model: anthropicModelName('claude-sonnet-4-5'),
      max_tokens: 4096,
      temperature: 0,
      messages: [{
        role: 'user',
        content: [
          { type: 'image', source: { type: 'base64', media_type: mimeType, data: imageBase64 } },
          { type: 'text', text: TRANSCRIPT_PROMPT },
        ],
      }],
    }),
  });

  if (!res.ok) {
    if (res.status === 429) throw new Error('TOO_MANY_REQUESTS');
    throw new Error(`HTTP_${res.status}`);
  }

  const json = await res.json();
  const text = (json.content?.[0]?.text ?? '').trim();

  if (!text) throw new Error('EMPTY_RESPONSE');
  if (text.startsWith('NOT_A_RECEIPT')) throw new Error('NOT_A_RECEIPT');
  if (text.startsWith('BLURRY'))        throw new Error('BLURRY');

  const words    = text.split(/\s+/);
  const unknowns = words.filter((w: string) => w === '[?]').length;
  if (unknowns / words.length > 0.5) throw new Error('BLURRY');

  return {
    transcript: text,
    tokens: {
      inputTokens:  json.usage?.input_tokens  ?? 0,
      outputTokens: json.usage?.output_tokens ?? 0,
    },
  };
}

// ─── Pass 2: structureTranscript ─────────────────────────────────────────────

export async function structureTranscript(
  transcript: string,
  provider: ProviderName,
): Promise<{ receipt: ParsedReceipt; tokens: PassTokens }> {
  const prompt = STRUCTURE_PROMPT.replace('{{TRANSCRIPT}}', transcript);

  switch (provider) {
    case 'gemini-2.0-flash':
    case 'gemini-2.5-flash':
    case 'gemini-1.5-pro':
      return _geminiStructure(prompt, geminiModelName(provider));
    case 'claude-sonnet-4-5':
      return _claudeStructure(prompt);
  }
}

async function _geminiStructure(
  prompt: string,
  model: string,
): Promise<{ receipt: ParsedReceipt; tokens: PassTokens }> {
  const res = await fetch(geminiUrl(model), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        responseMimeType: 'application/json',
        maxOutputTokens: 8192,
        temperature: 0,
        thinkingConfig: { thinkingBudget: 0 },
      },
    }),
  });

  if (!res.ok) {
    if (res.status === 429) await geminiParseQuotaError(res);
    throw new Error(`HTTP_${res.status}`);
  }

  const json = await res.json();
  const text = (json.candidates?.[0]?.content?.parts?.[0]?.text ?? '').trim();
  if (!text) throw new Error('EMPTY_RESPONSE');

  return {
    receipt: applyAutoCorrections(_parseReceiptJSON(text)),
    tokens: {
      inputTokens:  json.usageMetadata?.promptTokenCount     ?? 0,
      outputTokens: json.usageMetadata?.candidatesTokenCount ?? 0,
    },
  };
}

async function _claudeStructure(
  prompt: string,
): Promise<{ receipt: ParsedReceipt; tokens: PassTokens }> {
  const res = await fetch(ANTHROPIC_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_KEY,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model: anthropicModelName('claude-sonnet-4-5'),
      max_tokens: 8192,
      temperature: 0,
      messages: [{ role: 'user', content: prompt }],
    }),
  });

  if (!res.ok) {
    if (res.status === 429) throw new Error('TOO_MANY_REQUESTS');
    throw new Error(`HTTP_${res.status}`);
  }

  const json = await res.json();
  const text = (json.content?.[0]?.text ?? '').trim();
  if (!text) throw new Error('EMPTY_RESPONSE');

  return {
    receipt: applyAutoCorrections(_parseReceiptJSON(text)),
    tokens: {
      inputTokens:  json.usage?.input_tokens  ?? 0,
      outputTokens: json.usage?.output_tokens ?? 0,
    },
  };
}

// ─── Magic Fix: magicFix ─────────────────────────────────────────────────────

export async function magicFix(
  transcript: string,
  itemsSum: number,
  printedSubtotal: number,
  provider: ProviderName,
): Promise<ParsedReceipt | null> {
  const prompt = MAGIC_FIX_PROMPT
    .replace('{{TRANSCRIPT}}', transcript)
    .replace('{{ITEMS_SUM}}',  itemsSum.toFixed(2))
    .replace('{{TOTAL}}',      printedSubtotal.toFixed(2))
    .replace('{{DIFF}}',       Math.abs(itemsSum - printedSubtotal).toFixed(2));

  try {
    switch (provider) {
      case 'gemini-2.0-flash':
      case 'gemini-2.5-flash':
      case 'gemini-1.5-pro': {
        const res = await fetch(geminiUrl(geminiModelName(provider)), {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: {
              responseMimeType: 'application/json',
              maxOutputTokens: 8192,
              temperature: 0,
              thinkingConfig: { thinkingBudget: 0 },
            },
          }),
        });
        if (!res.ok) return null;
        const json = await res.json();
        const text = (json.candidates?.[0]?.content?.parts?.[0]?.text ?? '').trim();
        const p = JSON.parse(text);
        return p.error ? null : applyAutoCorrections(p as ParsedReceipt);
      }

      case 'claude-sonnet-4-5': {
        const res = await fetch(ANTHROPIC_URL, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': ANTHROPIC_KEY,
            'anthropic-version': '2023-06-01',
                },
          body: JSON.stringify({
            model: anthropicModelName('claude-sonnet-4-5'),
            max_tokens: 8192,
            temperature: 0,
            messages: [{ role: 'user', content: prompt }],
          }),
        });
        if (!res.ok) return null;
        const json = await res.json();
        const text = (json.content?.[0]?.text ?? '').trim();
        const p = JSON.parse(text);
        return p.error ? null : applyAutoCorrections(p as ParsedReceipt);
      }
    }
  } catch { return null; }
}

// ─── Shared JSON parser ───────────────────────────────────────────────────────

function _parseReceiptJSON(text: string): ParsedReceipt {
  // Strip markdown code fences some providers wrap JSON in
  const clean = text.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/, '').trim();
  let parsed: ParsedReceipt & { error?: string };
  try   { parsed = JSON.parse(clean); }
  catch { console.error('[adapter] bad JSON:', text); throw new Error('PARSE_ERROR'); }
  if (parsed.error) throw new Error(parsed.error);
  return parsed;
}

// ─── Prompts (preserved exactly — do not modify without testing) ──────────────

const TRANSCRIPT_PROMPT = `You are a LOW-LEVEL OCR engine.

You are NOT allowed to read or understand words.
You ONLY copy visual characters exactly as they appear on the page.

════════ HARD RULES ════════

1. DO NOT FIX TEXT
   If text looks wrong → keep it wrong.
   NEVER replace a character sequence with a real word.
   NEVER use language knowledge, food knowledge, or context.

2. DO NOT COMPLETE WORDS
   If the receipt says "לימונ" → output "לימונ", never "לימונדה".
   If the receipt says "רוסט" → output "רוסט", never "רוסטביף".

3. CHARACTER ACCURACY OVER MEANING
   A wrong character that matches the visual shape is CORRECT.
   A real food word that was not clearly visible is a FAILURE.

4. NO NORMALIZATION
   Keep spacing, punctuation, and symbols exactly as printed.

════════ OUTPUT FORMAT ════════

One receipt line per output line.
Copy EVERY line on the receipt — all of it, top to bottom, nothing skipped.
Do NOT decide what is an "item" vs a "header" — that is not your job. Just copy.
Preserve original order.

════════ EDGE CASES ════════

If the image is not a receipt, output only: NOT_A_RECEIPT
If the image is too blurry to read, output only: BLURRY`;

const STRUCTURE_PROMPT = `You are a JSON formatter for Israeli restaurant receipts.

RECEIPT TRANSCRIPT (read from image — treat as ground truth):
{{TRANSCRIPT}}

YOUR ONLY JOB: parse the numbers and copy the names exactly.

NAME RULE (absolute — no exceptions):
  Every item "name" MUST be copied character-for-character from the TRANSCRIPT above.
  The transcript is the source of truth. You cannot change, fix, translate, or improve any name.
  If transcript says "ג'ימזונה"  → name = "ג'ימזונה"   (not "לימונדה")
  If transcript says "במבוק ערק" → name = "במבוק ערק"  (not "יין")
  If a word looks like nonsense — keep it as nonsense. It is printed on the receipt.

RECEIPT LAYOUT (Tabit system — price LEFT, quantity, name RIGHT):
  "98.00  1 קבב טלה"          → price=98,  qty=1, name="קבב טלה"
  "136.00 2 רוסטביף סינטה"    → price=136, qty=2, name="רוסטביף סינטה"

Return ONLY this JSON (no markdown):
{
  "isReceipt": true,
  "receipt_type": "restaurant",
  "restaurantName": null,
  "currency": "ILS",
  "subtotal": number | null,
  "tax": number | null,
  "taxPercent": number | null,
  "serviceCharge": number | null,
  "total": number | null,
  "confidence": "high" | "medium" | "low",
  "items": [
    {
      "name": string,
      "quantity": number,
      "unit_price": number | null,
      "total_price": number | null,
      "price_missing": false,
      "sub_items": []
    }
  ]
}

- Skip: header, address, phone, totals row, tax row, QR code, loyalty text
- quantity defaults to 1
- unit_price = total_price ÷ quantity
- confidence = "low" if any price is missing`;

const MAGIC_FIX_PROMPT = `This receipt was parsed but the prices don't add up.

TRANSCRIPT (ground truth — do not change any name):
{{TRANSCRIPT}}

Items sum:     {{ITEMS_SUM}}
Printed total: {{TOTAL}}
Difference:    {{DIFF}}

Fix ONLY numeric values (prices, quantities). Every "name" must be copied verbatim from the TRANSCRIPT.
Common causes: decimal comma vs dot, skipped line, merged prices, wrong discount sign.

Return corrected JSON (no markdown):
{
  "isReceipt": true,
  "receipt_type": "restaurant",
  "restaurantName": null,
  "currency": "ILS",
  "subtotal": number | null,
  "tax": number | null,
  "taxPercent": number | null,
  "serviceCharge": number | null,
  "total": number | null,
  "confidence": "high" | "medium" | "low",
  "items": [
    {
      "name": string,
      "quantity": number,
      "unit_price": number | null,
      "total_price": number | null,
      "price_missing": boolean,
      "sub_items": [{ "name": string, "price": number | null }]
    }
  ]
}`;
